### ISSUE TITLE
🐞New DFO failed (1)

### ISSUE THREAD

**Issue by mdomox** [b-u-i-d-l/dfo-hub#10]
# **Describe the bug**

Deployment of DFO fails

# **To Reproduce**

Example:
1. Create new DFO
2. Insert DFO parameters
3. Accept 1st transaction in metamask
4. Accept 2nd transaction in metamask
5. Speed 2nd transaction in metamask
6. Transaction approved/mined in Ethereum
7. UI stuck in pending mode for the 2nd transaction . Although transaction is mined, the process does not continue. 

# **Expected behavior**

After the transaction is mined in ethereum, UI should pick up this and proceed with the process of DFO creation. 

# **Screenshots**

# **Web3 Scenario (please complete the following information):**

 - Device: Desktop
 - OS: Win 10
 - Browser Brave with metamask installed (internall wallet disabled)
 - Version 1.10.97
 - Provider Metamask

# **Additional context**

# **Reward**

If you want to be rewarded:
1) [Read carefully the DFOhub Community Guidelines and Reward Rules](https://www.notion.so/dfohub/Community-Guidelines-a03ceeab28254eb3944ab85320be70de)
2) [Join the DFOhub Discord Server](https://discord.gg/nHZ2bUd)
3) Discord Username and #: Cylon 3707
4) ETH Wallet: 0xA97860E2b549439818101C6e7e6D17bE25a4eA52

**Comment by alet89** [comment]
We have already solved this bug.... Reward sent https://etherscan.io/tx/0xb9e3575e464789ea00a4e48790bfb38b32301a1aed92dcba7dbdb35620211e57
+50BUIDL because is the first Backend bug ever discovered :)
