### ISSUE TITLE
🐞Creation of new DFO failed (2)

### ISSUE THREAD

**Issue by mdomox** [b-u-i-d-l/dfo-hub#11]
# **Describe the bug**

Deployment of DFO fails

# **To Reproduce**

Example:
1. Create new DFO
2. Insert DFO parameters (same parameters as the 1st attempt - see Failure (1) - Bug #10 )
3. Accept 1st transaction in metamask
4. Accept 2nd transaction in metamask
5. Accept 3rd transaction in metamask
6. 3rd transaction approved/mined in Ethereum
7. UI shows 3rd transaction as mined/completed
8. Process does not continue and throws an error : gas required exceeds allowance (12081559) or always failing transaction
7. Pressed the DEPLOY button repeatedly and the same error appears with the number in the brackets above changing from time to time.  

# **Expected behavior**

4th step to initiate and deployment of DFO to be finilized. 

# **Screenshots**

![Screenshot_4](https://user-images.githubusercontent.com/2255012/87137151-24bd4e80-c2a5-11ea-8f51-888d1590368b.png)

# **Web3 Scenario (please complete the following information):**

 - Device: Desktop
 - OS: Win 10
 - Browser Brave with metamask installed (internall wallet disabled)
 - Version 1.10.97
 - Provider Metamask

# **Additional context**

# **Reward**

If you want to be rewarded:
1) [Read carefully the DFOhub Community Guidelines and Reward Rules](https://www.notion.so/dfohub/Community-Guidelines-a03ceeab28254eb3944ab85320be70de)
2) [Join the DFOhub Discord Server](https://discord.gg/nHZ2bUd)
3) Discord Username and #: Cylon 3707
4) ETH Wallet: 0xA97860E2b549439818101C6e7e6D17bE25a4eA52

**Comment by alet89** [comment]
Thank you to have opened this issue :) As I sad yesterday, we’re working to find the issue 😊✌️ @marcovasapollo is personally working on it

**Comment by alet89** [comment]
We have already solved this bug.... Reward sent https://etherscan.io/tx/0xb9e3575e464789ea00a4e48790bfb38b32301a1aed92dcba7dbdb35620211e57
+50BUIDL because is the first Backend bug ever discovered :)
