### ISSUE TITLE
🐞Double creation of tokens

### ISSUE THREAD

**Issue by mdomox** [b-u-i-d-l/dfo-hub#12]
# **Describe the bug**

System allows to create the same token twice. Following up to the previous 2 bugs (bug #10 and bug #11 ), the outcome was that 2 sets of the token were created (by 2 different contracts).

# **To Reproduce**

Example:
1. Create DFO with token A - Process fails - See creation bug 1
2. Create second DFO with same parameters - Process fails  - See creation bug 2
3. 2 contracts create 2 tokens with same name and denomination 

# **Expected behavior**

System should check if same name exists and prompt for an error.

# **Screenshots**

![Screenshot_6](https://user-images.githubusercontent.com/2255012/87137893-49fe8c80-c2a6-11ea-8e3f-259f0d766e91.png)

# **Web3 Scenario (please complete the following information):**

 - Device: Desktop
 - OS: Win 10
 - Browser Brave with metamask installed (internall wallet disabled)
 - Version 1.10.97
 - Provider Metamask

# **Additional context**

https://etherscan.io/token/0x9eaC6f2e8A2391842f8028dA66eD6437B77c1740?a=0xa97860e2b549439818101c6e7e6d17be25a4ea52

https://etherscan.io/token/0x759d331a89475aec7658dc11a5bbd750d14de70b?a=0xa97860e2b549439818101c6e7e6d17be25a4ea52

# **Reward**

If you want to be rewarded:
1) [Read carefully the DFOhub Community Guidelines and Reward Rules](https://www.notion.so/dfohub/Community-Guidelines-a03ceeab28254eb3944ab85320be70de)
2) [Join the DFOhub Discord Server](https://discord.gg/nHZ2bUd)
3) Discord Username and #: Cylon 3707
4) ETH Wallet: 0xA97860E2b549439818101C6e7e6D17bE25a4eA52

**Comment by alet89** [comment]
We have already solved this bug.... Reward sent https://etherscan.io/tx/0xb9e3575e464789ea00a4e48790bfb38b32301a1aed92dcba7dbdb35620211e57
+50BUIDL because is the first Backend bug ever discovered :)
