### ISSUE TITLE
[UI] Button to run FixedInflation Microservice

### ISSUE THREAD

**Issue by vasapower** [b-u-i-d-l/dfo-hub#13]
Insert a "Run" button to run the `FixedInflation` Microservice every time the correct block is reached

**Comment by dashali20** [comment]
make add-tokenlist-extended asset_id=c60_t0x4Fabb145d64652a948d72533023f6E7A623C7C53

**Comment by dashali20** [comment]
make add-tokenlist asset_id=c60_t0x4Fabb145d64652a948d72533023f6E7A623C7C53-

**Comment by dashali20** [comment]
developer.trustwallet.com/assets/new-asset

**Comment by dashali20** [comment]
[ ] 

> ****
