### ISSUE TITLE
Loading Infos of DFOs older than the 0.1 Release

### ISSUE THREAD

**Issue by idontuseversioncontrol** [b-u-i-d-l/dfo-hub#21]
# **Describe the bug**

In some dapps (for example, ETHTurin), the Dapp/State page just loads indefinitely. 

# **To Reproduce**

1. Go to ETHTurin's page.
2. Navigate to Dapp/State.
3. Wait...

# **Expected behavior**

The page should load or an error message should appear.

# **Screenshots**

<img width="805" alt="Screen Shot 2020-08-20 at 18 40 23" src="https://user-images.githubusercontent.com/6132647/90800213-9fea3980-e314-11ea-95f0-c652fdb0533b.png">

# **Web3 Scenario (please complete the following information):**

- Env.: Desktop
- OS: macOS 10.15
- Browser: Safari
- Version: 13.1.2
- Provider: Metamask

# **Reward**

Discord Username and #: the4kman#4895
ETH Wallet: 0xaa8070363a48e6C245FAb811054bBF2B0B2853D7

**Comment by alet89** [comment]
Thank you for this issue, 

the oldest versions of DFOs during the R&D release < of the 0.1 are not supported by the Front-End... These are Test DFOs, but we're working on a versioning system to keep track of the updates and the DFOs versions.

This is a well known Issue

Reward Paid: https://etherscan.io/tx/0x9222ec744813e4c96e15625d14f5b4bf7f74b2dec663a1d6b55c1527edd0a938

**Comment by alet89** [comment]
Solved
