### ISSUE TITLE
🐞In some dapps, the Dapp/Functions page doesn't load if you switch between Dapp/Functions and Dapp/State fast

### ISSUE THREAD

**Issue by idontuseversioncontrol** [b-u-i-d-l/dfo-hub#22]
# **Describe the bug**

🐞In some dapps (for example, ETHTurin), the Dapp/Functions page doesn't load if you switch between Dapp/Functions and Dapp/State fast.

# **To Reproduce**

1. Go to ETHTurin's page.
2. Navigate to Dapp/State.
3. Navigate between Dapp/State and Dapp/Functions a few times.
4. Dapp/Functions will eventually be empty.

# **Expected behavior**

The contents of the page should appear

# **Screenshots**

![ezgif-4-2a224521267a](https://user-images.githubusercontent.com/6132647/90800844-7aa9fb00-e315-11ea-943d-98ebee6ff8d6.gif)

# **Web3 Scenario (please complete the following information):**

- Env.: Desktop
- OS: macOS 10.15
- Browser: Safari
- Version: 13.1.2
- Provider: Metamask

# **Reward**

Discord Username and #: the4kman#4895
ETH Wallet: 0xaa8070363a48e6C245FAb811054bBF2B0B2853D7

**Comment by alet89** [comment]
This is a collateral effect of this issue: https://github.com/b-u-i-d-l/dfo-hub/issues/21
