### ISSUE TITLE
Failed to load "No Liquidity" Message in DeFi > Token

### ISSUE THREAD

**Issue by idontuseversioncontrol** [b-u-i-d-l/dfo-hub#23]
# **Describe the bug**

 In some dapps (for example, LIPS), the Dex Liquidity section on the DeFi/Token page doesn't load, the loading spinner just spins indefinitely.

# **To Reproduce**

1. Go to LIPS's page.
2. Navigate to DeFi/Token and look at the Dex Liquidity page.
3. Wait...

# **Expected behavior**

The page should load or an error message should appear.

# **Screenshots**

<img width="1036" alt="Screen Shot 2020-08-20 at 18 50 39" src="https://user-images.githubusercontent.com/6132647/90801329-13407b00-e316-11ea-94e2-36bd4487d357.png">

# **Web3 Scenario (please complete the following information):**

- Env.: Desktop
- OS: macOS 10.15
- Browser: Safari
- Version: 13.1.2
- Provider: Metamask

# **Reward**

Discord Username and #: the4kman#4895
ETH Wallet: 0xaa8070363a48e6C245FAb811054bBF2B0B2853D7

**Comment by alet89** [comment]
Thank you for the report, this is a bug, basically when there are no pairs for the token, we fail to enter the message: "no Liquidity For This Token"

Reward Paid: https://etherscan.io/tx/0x1f16594d184ec40ea31e2877b46dc94c9df7036dbff88f374e0749ea5d49f087

**Comment by alet89** [comment]
Solved
