### ISSUE TITLE
🐞The Read button on the Dapp/Functions page does not have a pointer cursor style

### ISSUE THREAD

**Issue by idontuseversioncontrol** [b-u-i-d-l/dfo-hub#24]
# **Describe the bug**

The Read button on the Dapp/Functions page, visible after pressing Query next to a function, does not have a pointer cursor style, unlike the rest of the buttons on that page, despite being clickable.

# **To Reproduce**

Example:
1. Go to a dapp's page and navigate to Dapp/Functions.
2. Click on the Query button next to a function.
3. Hover your mouse over the button.

# **Expected behavior**

The pointer cursor should appear.

# **Screenshots**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6132647/90802638-d37a9300-e317-11ea-9677-f6f5cae0a36b.gif)
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/6132647/90802641-d5445680-e317-11ea-8981-7fb58f1e19bb.gif)

# **Web3 Scenario (please complete the following information):**

- Env.: Desktop
- OS: macOS 10.15
- Browser: Safari
- Version: 13.1.2
- Provider: Metamask

# **Reward**

Discord Username and #: the4kman#4895
ETH Wallet: 0xaa8070363a48e6C245FAb811054bBF2B0B2853D7

**Comment by alet89** [comment]
Thank you for the report, already solved

Reward Paid: https://etherscan.io/tx/0xcfc288dec498ef13acb3a89927fd034ae49cdfe6c301875052de05dda6b6c982
