### ISSUE TITLE
🐞

### ISSUE THREAD

**Issue by MrDobalina** [b-u-i-d-l/dfo-hub#30]
# **Describe the bug**

After a voting proposal passed successfully the button to withdraw my tokens (BAST in this case) from the smart contract was not available. 

# **To Reproduce**

1. From DFOhub main page, I clicked on BAST.
2. I then clicked on the Governance tab.
3. I then clicked on the Proposals tab.
4. Other members of BAST told me that I would need to click on the info button beside the appropriate proposal to see a withdraw button, but once I did this there was no withdraw button available.

# **Expected behavior**

A withdraw button is expected to be available for me to remove my tokens from the voting smart contract.

# **Screenshots**

![image](https://user-images.githubusercontent.com/46727233/93241816-df5d4780-f753-11ea-9a52-ad35e063e58f.png)
I have added a screen shot of the area of where the withdraw button should be.

# **Web3 Scenario (please complete the following information):**

 - Device: Desktop PC
 - OS: Windows 10 
 - Browser: Chrome
 - Version: Version 85.0.4183.83 (Official Build) (64-bit)
 - Provider: Metamask

# **Additional context**

Some of the members of the BAST community and myself were doing testing to try to figure out the problem. I personally tested:
Different browser: BRAVE browser.
Different computer with same setup (windows 10 + chrome + metamask).
I turned off all extensions in chrome except for metamask then re-tested. I also turned off the developer mode in Chrome then re-tested. I tried changing from nighttime mode to daytime mode using the DFOhub button then re-tested. I tried refreshing many many times and even CTRL+F5 but nothing worked. (apparently some members of BAST did get the withdraw button to reappear after many refreshes but I was not successful with this).
One BAST member noticed that if he connected a wallet to metamask that didn't have any BAST at all (none in the vote contract or in the wallet) he could see the withdraw button, but as soon as he connected his wallet with BAST in the vote contract he could not see the button.

# **Reward**

If you want to be rewarded:
1) [Read carefully the DFOhub Community Guidelines and Reward Rules](https://www.notion.so/dfohub/Community-Guidelines-a03ceeab28254eb3944ab85320be70de)
2) [Join the DFOhub Discord Server](https://discord.gg/nHZ2bUd)
3) Discord Username and #: Crypto P.I.   #6930
4) ETH Wallet: 0x1C6c4B0Bb7778024587F664469Ec1B8aDb34f835

**Comment by vasapower** [comment]
We made some updates in the proposals refresh logic which improved the user experience of the Withdraw button. 
Please, tempestively notify us through this issue if the problem persists, so we can grab the correct moment in wich the trouble occurs.

Thank you!
