### ISSUE TITLE
💬 Whats happened if I don't do every transactions requested by the GUI Wizard deploying a DFO?

### ISSUE THREAD

**Issue by ghost** [b-u-i-d-l/dfo-hub#4]
# **Describe the bug**

UI on DFO Hub main page does not show newly deployed DFO. Also does not show when searched (Noved).

# **To Reproduce**

Went through the steps of launching a DFO, and submitted the transaction. The transaction was successful, and shows the contract and token on etherscan. The front end however did not update.

# **Expected behavior**

Expected the front end to auto update after the transaction cleared.

# **Screenshots**

# **Web3 Scenario (please complete the following information):**

 - Device: [e.g. Desktop, Smartphone] Desktop
 - Browser [e.g. chrome, safari] Chrome
 - Provider [e.g. Metamask] 

# **Additional context**

# **Reward**

If you want to be rewarded:
1) [Read carefully the DFOhub Community Guidelines and Reward Rules](https://www.notion.so/dfohub/Community-Guidelines-a03ceeab28254eb3944ab85320be70de)
2) [Join the DFOhub Discord Server](https://discord.gg/nHZ2bUd)
3) Discord Username and #: Noved #1361
4) ETH Wallet: 0x58AA4075099bD491A49F3A21807f37f275AD2e3f

**Comment by alet89** [comment]
Hi Nove, thank you for posting this bug :)

Can you share the transactions you made to deploy a DFO and the rules you set during the creation

**Comment by ghost** [comment]
Transaction Hash:
0x51c609998a8359f34148d839b84f246c7516890a681e12acf606ec520fdc8d34

Inputs: (as I remember, was hoping I could see the summary on the dashboard after):
10k supply

community driven

survey length: 20 blocks
Survey Quorum: %30 (or 40%?)

Total reward supply? 5000
Single reward 100?

emergency length 50 blocks

Penalty:
200

Also: 

For UX, I was unsure what Single reward meant in the context of the DFO (same for survey length, maybe an (i) explanations/hints on the rule mechanism). The reward split between voters? 

Also are these rules changeable in the future?

**Comment by alet89** [comment]
🤔 you made only the first transaction? When you deploy a DFO using dfohub.eth there are more than one transaction in a wizard to successful deploy it, are you sure you made every transaction needed?

"The reward split between voters?"
Community rewards mean that every time someone creates a proposal, if the proposal pass, the proposer earn a reward. This is a useful practise to incentivise people in an anonymous way to develop together the depp on top

"Also are these rules changeable in the future?"
Yes DFOs are mocroservices based dapps so can propose a change every time you need after the deployment :)

**Comment by ghost** [comment]
I only received one transaction popup for .13 eth ($27). 

Let me know if I can retrieve any specific information that could be of more help :), off to sleep here

**Comment by alet89** [comment]
I tried to recreate your scenario into the dfohub.eth, but the wizard is asking me to make 4 transactions 🤔

Can you share me more details about the web 3 provider you used? 

Can you retry to deploy a DFO and share us a screen about what you see from the deploy wizard, before making the first transaction?

**Comment by ghost** [comment]
![DFO](https://user-images.githubusercontent.com/35188616/82805929-0eb51500-9e42-11ea-9a73-ea3aed41141a.jpg)

**Comment by alet89** [comment]
Yep everything seems working fine, if you see the snap, you have a list of transactions to do..

After you made the first transaction, the wizard will set a ✅ on it and you have to press the button deploy to deploy the second transactions, until every listed transactions are done.

After that the DFO is successfully deployed and you’ll be redirect automatically to the new DFO explorer.

If you don’t make every transaction the DFO is not successfully deployed

**Comment by ghost** [comment]
Awe I see. 

I may have been too excited....lol. So I had pushed confirm on MM, but didnt push the "Deploy" button on the DFOhub page itself, after the transaction went through? 

I was expecting the wizard to launch a new page and auto deploy with a summary from the MM confirmation. Didn't realize further interaction was required.

Is it possible to interact for the second transaction for completion if a user makes a mistake such as mine?

**Comment by alet89** [comment]
Unfortunately is not possible at the moment.
