### ISSUE TITLE
🐞 Proposals Loading Order

### ISSUE THREAD

**Issue by ghost** [b-u-i-d-l/dfo-hub#6]
# **Describe the bug**

Proposals populate with the most recent. However after 38 seconds (i.e. while reading a description of a proposal), more proposals populate, older ones move ahead of the more recent, and I have to scroll down to keep reading the description of the more recent.)  

# **To Reproduce**

Click on DFOHUB, then over to the PROPOSAL tab. 
Click on more of a description of the most recent. 
Wait 38 seconds as proposals continue to load.
The older Proposals will appear at the top, pushing more recent proposals to bottom.

# **Expected behavior**

I expect the newest proposals to load first, and stay at the top, while older proposals load to the bottom (to allow time to read the first loaded proposals).

# **Screenshots**

![DFOproposalload](https://user-images.githubusercontent.com/35188616/83708335-4c9c0100-a5d9-11ea-8c38-bfa3adbc3475.png)

# **Web3 Scenario (please complete the following information):**

MetaMask

# **Additional context**

0x58AA4075099bD491A49F3A21807f37f275AD2e3f

**Comment by marcovasapollo** [comment]
Thank you so much for the report!

This is a well-known problem that can be solved only now that all the recent updates to the Core Contracts have been completed. 
We were already working on it and the fix will be published in the next few hours.

Will keep you noticed of it!

**Comment by alet89** [comment]
In the next hours, we’ll add this bug into the bug report section on our Notion and we’ll send you the reward 😊 Thanks ✌️

**Comment by alet89** [comment]
We successfully sent 100 BUIDL for this UI Bug Reporting :) https://etherscan.io/tx/0x752b30fe0e0b4e936e460448e44edc9c8a55f6bd8f99ee485e9f7ae005275f84 
Thanks for your help!

**Comment by ghost** [comment]
Glad to have helped, Thank you! @alet89 @marcovasapollo

**Comment by alet89** [comment]
I reopened the issue to write here before we’ll solve this bug 😊

**Comment by vasapower** [comment]
Thank you so much for the report! 

This was a well-known problem that could be solved only after the recent massive updates to the Core Contracts we made in these days.

The bugfix has just been published and you can now enjoy it. ✌
